version: '1.8.{build}'

configuration: Release
platform: Any CPU
image: Visual Studio 2017
shallow_clone: true

install:
#- cmd: choco install InnoSetup
- cmd: SET PATH=%PATH%;C:\Program Files (x86)\Inno Setup 5

before_build:
- nuget restore -Verbosity quiet Source\MOSA.sln

build:
  verbosity: minimal
  parallel: true
  project: Source\MOSA.sln
  publish_nuget: true

after_build:
- cmd: ISCC.exe Source\Inno-Setup-Script\Mosa-Installer.iss

build_script:

after_test:

nuget:
  project_feed: true

test: off

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

artifacts:
- path: 'bin\MOSA Installer\MOSA-Installer.exe'

